apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: fulcrum
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: "fulcrum"
        static_configs:
          - targets: ["fulcrum:80"]